### ISSUE TITLE
[BUG]: 分析失败, 请稍后重试

### ISSUE THREAD

**Issue by zhulinyv** [A-kirami/nonebot-plugin-savor#1]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确定问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [X] 我愿意帮助修复此问题。（这会将您指定为此问题的受理人并自动创建修复分支）

### 影响版本

0.1.1

### 问题描述

如附图，出现报错。如何解决该问题呢？
OSError: cannot write mode RGBA as JPEG

### 额外补充

![image](https://user-images.githubusercontent.com/66541860/197671335-5ba317a8-0706-4c30-a574-bcd45a547ed6.png)
![image](https://user-images.githubusercontent.com/66541860/197671367-9faa5899-504f-4e58-a03e-cf6750fcfb37.png)

**Comment by Kiana1314** [comment]
大佬 更新完我这还是分析失败
![P7@4){%)}`MLHR(}6DHHBPV](https://user-images.githubusercontent.com/107671434/197758313-3ecfbc0b-ffb1-49db-ac73-8c5126e4055a.png)

**Comment by A-kirami** [comment]
> 大佬 更新完我这还是分析失败
> ![P7@4){%)}`MLHR(}6DHHBPV](https://user-images.githubusercontent.com/107671434/197758313-3ecfbc0b-ffb1-49db-ac73-8c5126e4055a.png)
> 

这是另一个错误了 另开一个issue吧
