### ISSUE TITLE
[BUG]: 分析失败, 请稍后重试 KeyError: 'hash'

### ISSUE THREAD

**Issue by Kiana1314** [A-kirami/nonebot-plugin-savor#3]
### 报告清单

- [X] 我已仔细阅读并了解上述注意事项。
- [X] 我已使用最新版本测试过，确定问题依旧存在。
- [X] 我确定在 [GitHub Issues](../issues) 中没有相同或相似的问题。
- [ ] 我愿意帮助修复此问题。（这会将您指定为此问题的受理人并自动创建修复分支）

### 影响版本

0.1.2

### 问题描述

分析失败, 请稍后重试 
KeyError: 'hash'
![P7@4){%)}`MLHR(}6DHHBPV](https://user-images.githubusercontent.com/107671434/197764306-6e42b5d3-639a-4c3d-9247-cb77672052e9.png)

### 重现步骤

鉴赏+图片

**Comment by ElainaFanBoy** [comment]
我也

**Comment by a930389426** [comment]
我也

**Comment by CCYellowStar** [comment]
好像是api变了

**Comment by Cvandia** [comment]
我也

**Comment by CCYellowStar** [comment]
我自己换了个api

**Comment by Cvandia** [comment]
> 

能发下吗

**Comment by CCYellowStar** [comment]
> > 
> 
> 能发下吗

你直接看我分支吧

**Comment by A-kirami** [comment]
已修复，请更新到最新版本
